version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"

