CREATE DATABASE requests;
CREATE DATABASE reports;

\c requests;

CREATE TABLE requests (
    id SERIAL PRIMARY KEY,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    body JSONB NOT NULL,
    isDone INTEGER DEFAULT 0
);

CREATE TABLE responses (
    id SERIAL PRIMARY KEY,
    request_id INTEGER NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    body JSONB NOT NULL,
    FOREIGN KEY(request_id) REFERENCES requests(id)
);